Feature accounts
TheMazeIsAmazing/tle2team6-ml5-2022-2023 pull request #11
Opened 2023-06-15 20:18 UTC by starblaster69

account code to login, register, update and delete should be working now

2023-06-15 20:31 UTC, TheMazeIsAmazing requested changes
Ziet er goed uit!
Pas wel nog een paar query's aan om ze helemaal veilig te maken.

Wat zijn de fridge_friend/users.frm en fridge_friend/users.ibd bestanden? Is dat voor het hashen van de wachtwoorden?

2023-06-15 20:31 UTC, TheMazeIsAmazing commented on accounts/delete.php
> +        "DELETE FROM users INNER JOIN product_user WHERE users.id= product_user.user_id and users.id=$userId");
Om het veilig te maken is het handig om niet direct variabelen in een query te zetten...
Bijv: van:  "DELETE FROM users INNER JOIN product_user WHERE users.id= product_user.user_id and users.id=$userId");
Naar:  "DELETE FROM users INNER JOIN product_user WHERE users.id= product_user.user_id and users.id='$userId'");

2023-06-15 20:31 UTC, TheMazeIsAmazing commented on accounts/register.php
> +            VALUES ('$email', '$phone', '$hash', '$name', '$familySize')"
En dan heb je ze hier wel al tussen '' staan 🙃

2023-06-21 12:56 UTC, starblaster69 reviewed
resolved pull request feedback

2023-06-21 12:59 UTC, TheMazeIsAmazing approved these changes

2023-06-21 13:00 UTC, merged